### PR TITLE
1421 plug crash

### PR DESCRIPTION
**Pull request by ScottKolmarWFI**
# Pull Request Checklist

Thank you for contributing to the SuperCowPowers SageWorks project. Please make sure you've completed the following tasks before submitting your pull request:

#### GENERAL
- [  ] I've read the [CONTRIBUTING](https://github.com/SuperCowPowers/sageworks/blob/main/CONTRIBUTING.md) document.
- [  ] I've merged 'main' into my PR branch (like today's main)

#### TESTING (run 'tox' for local testing)
Endpoint test is failing for wine classification, because the endpoint doesn't exist.
This has nothing to do with this PR so I'll just leave that to you.

#### UI (Web Interface/Components)
- [  ] I've run sageworks/applications/aws_dashboard/dashboard
- [  ] I've tested the UI and scanned the log output for any issues

#### DOCUMENTATION
- [  ] I've updated the documentation accordingly

#### REVIEW 
- [  ] I've added (or will add) a reviewer to the PR
- [  ] I'll address any comments/request from reviewer
- [  ] I will delete the branch after the PR is merged 

#### Notes
An SCP Developer/reviewer may make direct changes to your branch. A follow up issue might be created or asked for. Branches are empheral, they should/will be deleted after the PR is merged. Do not reuse an old branch, if a change needs to be made pull a new branch off of main.

## Description of Changes

Model plugins need the inference run to be passed to update contents, so I added the inference run selector value as an input to the plugin callback for the models page.

### CODE REVIEW

**Comment by brifordwylie** [comment]
So I understand the change and the rational behind it, but not all model plugins need the currently selected inference_run. Most model plugins will simply take the model object as an argument. Perhaps we can add a '**kwargs' to the update_content method, so that plugins that need additional info can have it passed in. Also let's put [ x ] into the PR checklist :)

**Comment by ScottKolmarWFI** [comment]
Pull Request Checklist
Thank you for contributing to the SuperCowPowers SageWorks project. Please make sure you've completed the following tasks before submitting your pull request:

GENERAL
[ x] I've read the [CONTRIBUTING](https://github.com/SuperCowPowers/sageworks/blob/main/CONTRIBUTING.md) document.
[x ] I've merged 'main' into my PR branch (like today's main)

TESTING (run 'tox' for local testing)
Endpoint test is failing for wine classification, because the endpoint doesn't exist.
This has nothing to do with this PR so I'll just leave that to you.

UI (Web Interface/Components)
[x ] I've run sageworks/applications/aws_dashboard/dashboard
[x ] I've tested the UI and scanned the log output for any issues

DOCUMENTATION
[ unsure, I guess] I've updated the documentation accordingly

REVIEW
[ x] I've added (or will add) a reviewer to the PR
[ i promise, i swear on everything that's holy, I will honor this sacred agreement] I'll address any comments/request from reviewer
[on my honor ] I will delete the branch after the PR is merged


Description of Changes
**kwargs added to PluginInterface.update_contents(), and inference_run added as a kwarg to the callback in the model page. I tested this out with a new ModelTestPlugin that does not have inference_run as an explicit kwarg in it's update_contents, and it loaded without issue, so I think that covers it.

**Comment by brifordwylie** [comment]
Okay, I like the **kwargs idea... best of all worlds and one of my favorite 'pleasantly beautiful' corners of Python. 

Couple of minutia;
- Lets just edit the checklist in place next time :)
- Add a reviewer to the PR (top right corner of this page)

**Review by brifordwylie — APPROVED** [review]
Looks great! Short and sweet, double optimized.

**Pull request merged**
