### PR TITLE
Fix/web components

### LINKED ISSUE #250: Organize, clean up, improve the web_components
Okay, so the current set of web_components was developed quickly :)

They need a heavy handed overhaul:
- Make them 'good' components with a semi-standard interface (try to use DataFrames as much as possible)
- Document the interface
- Review internal code, some classes should maybe be combined
- Box plot is probably a lot like violin plot... should we combine them and put in a 'type' parameter or leave them separate?
- Obviously skip the classes with `mock_` at the beginning as those will be replaced with 'real' components later

Screenshot 2023-05-31 at 10 58 05 AM

### LINKED ISSUE #257: Violin Plot 'growth' logic
Okay, so when the violin plot has just a few plots the current height is fine, but where there's lots of plots it should grow in height so that the plots are 'smooshed'

Screenshot 2023-06-07 at 11 32 21 AM

### PR DESCRIPTION
**Pull request by luiztauffer**
WIP

- [x] Fix #257 
- [x] Fix #250

### CODE REVIEW

**Comment by giupb** [comment]
The implemented logic determines the height of the figure using a logarithmic function. The more rows the figure has, the smaller the size of the subplots in each row. The maximum and minimum values of the subplots in each row are defined within the "calculate_height" function as "base_height" and "min_height" respectively.

image

**Comment by giupb** [comment]
Following @luiztauffer suggestion in Slack, I simplified the logic that determines the height of the figure. Instead of using a logarithmic function, the height now grows linearly based on the number of subplot rows.

**Comment by brifordwylie** [comment]
lgtm, please merge when you think it's ready

**Comment by giupb** [comment]
In addition to the adjustments in the figure's height, in this pull request, we also merged the web_components violin_plot and box_plot into a single component called figures_plots, which is already being used. 
We also merged the web_components data_source_details and feature_set_details into a single component called data_and_feature_details, which is also already being used. 
I did not delete the components that were replaced; I leave that decision up to you, @brifordwylie. 
We can also change the names of the new components if there are other names that we prefer.

I believe the issues resolved by this PR were #250 and #257

**Comment by brifordwylie** [comment]
@luiztauffer sounds good, please delete the replaced components and merge this whenever is convenient.

**Pull request merged**
