### PR TITLE
Fix/artifact page load

### LINKED ISSUE #260: Details artifact page always loads the first row
Regardless of the row clicked on a specific artifact table on the home page, when the artifact page loads, it always displays the data from the first row of that artifact table.

For example, if I click on the second row of the Data Sources table, when the Data Sources details page loads, it displays the details of the first Data Source:
image
image

It would be great if, when the user clicks on a specific artifact on an artifact table, the details page shows the details of that specific artifact instead of the first one.

### PR DESCRIPTION
**Pull request by giupb**
WIP

Fix #260 

To do for #260:
- [ ] Implement logic in the feature sets page
- [ ] Implement logic in the models page
- [ ] Implement logic in the endpoints page

### CODE REVIEW

**Comment by giupb** [comment]
I implemented a solution for the Data Source page. It's working, but I don't think it's the best solution.

Here are some key points to consider:

- Hyperlink names: For each row in the "name" column, I added a query parameter to the existing artifact page URL (I did not modify the AWS Athena hyperlink that is also present in the name column). This allows the callback on the data source page to identify which row was clicked on the home page. However, I am unsure if this could potentially cause errors in other parts of the app, apart from one aspect:
  - When clicking on the column names in the artifact pages, it leads to an error page. Prior to that error, the link opens the same artifact page again (which seems unnecessary). If we decide to keep this hyperlink strategy, to address this error, I suggest removing the hyperlink from the name portion of the column and retaining it solely in the Athena query.
- Sleep statement usage: I had to include a sleep statement to prevent the selected row from being replaced by row [0] during the callback that verifies the actual selected row.

Please feel free to add any additional insights or suggestions to further enhance the solution.

**Comment by brifordwylie** [comment]
@giupb this look okay...I tried it out and seems to work good. @luiztauffer made a good observation about how UI's grow in complexity, so as a team we should keep that in mind as we go forward.

Also, when you click back to the main page.. there's kinda a weird red box... I think maybe I'd prefer to have NO selection box on the main page as it doesn't really make sense for the main page:
Screenshot 2023-06-14 at 12 00 34 PM

**Comment by brifordwylie** [comment]
@giupb @luiztauffer Hey, so as part of this ticket can we have the `web_components/table.py` take an option for cell selectable and then for the main/top page maybe turn it off ?  The main page looks a bit odd after clicking on a data source :)
Screenshot 2023-06-15 at 7 51 42 AM

**Comment by giupb** [comment]
@brifordwylie 
I fixed the main logic of this PR, which previously even required the sleep function, and now it's cleaner and more coherent. 
I also resolved the issue with the hotpink color that appears when a cell is selected. (For now, it's only working on the tables of the main page.)

**Comment by giupb** [comment]
@brifordwylie 
I fixed the color issue in the data source page too.
Give a try and let me know what you think.

**Comment by brifordwylie** [comment]
So, the UI looks good... I am a bit concerned about hard coding colors... we have an upcoming ticket on switching themes... but anyway, looks good for now, I would go ahead and merge this.

@giupb can you make a ticket related to the themes where colors are 'looked up' based on the current theme?

**Comment by brifordwylie** [comment]
Oh.. also I noticed this in the log output.. it seems to happen occasionally... not sure the root cause...

```
2023-06-15 11:02:03 (_internal.py:224) INFO 127.0.0.1 - - [15/Jun/2023 11:02:03] "POST /_dash-update-component HTTP/1.1" 204 -
2023-06-15 11:02:03 (app.py:1741) ERROR Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/dash/dash.py", line 1283, in dispatch
    ctx.run(
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/dash/_callback.py", line 450, in add_context
    output_value = func(*func_args, **func_kwargs)  # %% callback invoked %%
TypeError: refresh_data_timer.<locals>.time_updated() missing 1 required positional argument: 'url_query'
```

Found a second error...
```
Traceback (most recent call last):
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/briford/.pyenv/versions/py310/lib/python3.10/site-packages/dash/dash.py", line 1279, in dispatch
    raise KeyError(msg) from missing_callback_function
KeyError: "Callback function not found for output '..data-sources-url.search...data_sources_table.selected_rows..', perhaps you forgot to prepend the '@'?"
```

**Comment by brifordwylie** [comment]
I've saved this PR in a local repo for save keeping if we need it. Closing this as it's in conflict with current main.

**Pull request closed without merging**
